service: gestion-vuelos-api

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  environment:
    USERS_TABLE: Usuarios
    AEROLINEAS_TABLE: Aerolineas
    VUELOS_TABLE: Vuelos

functions:
  # USUARIOS
  createUsuario:
    handler: create_usuario.lambda_handler
    events:
      - http:
          path: /usuarios
          method: post

  searchUsuario:
    handler: search_usuario.lambda_handler
    events:
      - http:
          path: /usuarios
          method: get

  updateUsuario:
    handler: update_usuario.lambda_handler
    events:
      - http:
          path: /usuarios
          method: put

  deleteUsuario:
    handler: delete_usuario.lambda_handler
    events:
      - http:
          path: /usuarios
          method: delete

  # AEROLINEAS
  createAerolinea:
    handler: create_aerolinea.lambda_handler
    events:
      - http:
          path: /aerolineas
          method: post

  searchAerolinea:
    handler: search_aerolinea.lambda_handler
    events:
      - http:
          path: /aerolineas
          method: get

  updateAerolinea:
    handler: update_aerolinea.lambda_handler
    events:
      - http:
          path: /aerolineas
          method: put

  deleteAerolinea:
    handler: delete_aerolinea.lambda_handler
    events:
      - http:
          path: /aerolineas
          method: delete

  # VUELOS
  createVuelo:
    handler: create_vuelo.lambda_handler
    events:
      - http:
          path: /vuelos
          method: post

  searchVuelo:
    handler: search_vuelo.lambda_handler
    events:
      - http:
          path: /vuelos
          method: get

  updateVuelo:
    handler: update_vuelo.lambda_handler
    events:
      - http:
          path: /vuelos
          method: put

  deleteVuelo:
    handler: delete_vuelo.lambda_handler
    events:
      - http:
          path: /vuelos
          method: delete

resources:
  Resources:
    # Tabla Usuarios
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id_usuario
            AttributeType: S
        KeySchema:
          - AttributeName: id_usuario
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # Tabla Aerolíneas
    AerolineasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.AEROLINEAS_TABLE}
        AttributeDefinitions:
          - AttributeName: id_aerolinea
            AttributeType: S
        KeySchema:
          - AttributeName: id_aerolinea
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # Tabla Vuelos
    VuelosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.VUELOS_TABLE}
        AttributeDefinitions:
          - AttributeName: id_vuelo
            AttributeType: S
        KeySchema:
          - AttributeName: id_vuelo
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
